apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCaietrBk88AECYADKBGgCmGd0MWzLYShPrMbLKBEkJ/8wCfW0SxE8ZK7Ko1KpRNiQNMkBsgnzTVFkstHvyFpwzlXCoMw9D9mgxtEa5WGNu+upnA4mE2EXY3teRgUNL/cI4lf+x0ljRzL+7WHGBG6voEN7vMXwKKcNMJBmVrjTs77J2uvYEusG3+9GhZtll2ojVFWCwoFzQSmDeCausmNKUuCDXtC0zo541m3/thGMqc9drJ/zayiGAAAFnOQ4Y3ipm8W8Jw2IS3DdBVVf8e3S6T/v6WXD1yqMmj2XVdy9d/XEAQKPZXNEv5GEwiujAE/pc0u4VQ7mP3SN9RydIKtApKhD2hULQ+Wffvg6bAO85bUGCHPb8KK5sH677wWiihK99thBmDuWJMuT2Pmn/qa2ySiUeOdwJQj2jxyBrpXh43gc7wZ/mjd/JR30GxxqUzha8HkXpPdzgwAl6uljmqqj7GUA6laggMWBsgorhdCDZcVEmRLlV+3uFk5UooJsqLp4XLCa8tgsN5MeV7gcQVCvXcmDdT6Bc8olc8z+XTeQHUpJ9l9GDFdYGokdNk8s8JKDkrCmWwxyuIodnLRZ2XmJXsMn0zD5EMDmiau3ASRpplA58sQ9nPQG99+CSC9gO5YrEkwFOmUDTkGhUxJgWJXSrWmjgVWoy4uJTyintlZ1bFMn5EfFYeAnp3dC9n5ObAEeMT1H02nSm3eWKhFBc0bLQPoMQ5qtmOUGLKKi+COKUC4ny7wc7QXk8
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
